In [7]:
import numpy as np
arr=np.zeros(3)
arr


array([0., 0., 0.])

In [9]:
arr1=np.zeros([3,4])
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
arr2=np.zeros([3,4,5])
arr2

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [11]:
arr3=np.ones([3,4])
arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
arr4=np.empty([2,3,4])
arr4

array([[[1.36981400e-316, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [1.56836199e-319, 0.00000000e+000, 0.00000000e+000,
         1.06099910e-313],
        [0.00000000e+000, 0.00000000e+000, 1.56836199e-319,
         0.00000000e+000]],

       [[1.14129164e-320, 1.27319882e-313, 0.00000000e+000,
         0.00000000e+000],
        [1.48539908e-313, 0.00000000e+000, 0.00000000e+000,
         1.56836199e-319],
        [0.00000000e+000, 0.00000000e+000, 1.06099924e-313,
         0.00000000e+000]]])

In [14]:
arr5=np.eye(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
arr6=np.diag([2,3])
arr6

array([[2, 0],
       [0, 3]])

In [17]:
arr=np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [19]:
arr=np.linspace(2,7,4)
arr

array([2.        , 3.66666667, 5.33333333, 7.        ])

In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
arr.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [19]:
import numpy as np
arr= np.array([1,2,3,4],'b')
arr.dtype

dtype('int8')

In [17]:
arr1=np.array([1.1])
arr1.dtype

dtype('float64')

In [23]:
arr4=np.array([1,2,3,4],'longlong')
arr4

array([1, 2, 3, 4], dtype=int64)